// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWwV7EAjeVKI2n3ZXTmzJpBBBXxIZBWmw',
    appId: '1:167560947670:web:2bf81a08ea7b2ec89f2677',
    messagingSenderId: '167560947670',
    projectId: 'foodpandaclone-f3bdc',
    authDomain: 'foodpandaclone-f3bdc.firebaseapp.com',
    storageBucket: 'foodpandaclone-f3bdc.appspot.com',
    measurementId: 'G-3Q25SXXT28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOaUgIPgVvNnFAGUonhLk4dg79nORokec',
    appId: '1:167560947670:android:1a798f9e79668a919f2677',
    messagingSenderId: '167560947670',
    projectId: 'foodpandaclone-f3bdc',
    storageBucket: 'foodpandaclone-f3bdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvk1HKpXb07WZvUEedFIBX3qRycj1vicw',
    appId: '1:167560947670:ios:d1404b6faa3acdba9f2677',
    messagingSenderId: '167560947670',
    projectId: 'foodpandaclone-f3bdc',
    storageBucket: 'foodpandaclone-f3bdc.appspot.com',
    iosBundleId: 'com.example.sellersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvk1HKpXb07WZvUEedFIBX3qRycj1vicw',
    appId: '1:167560947670:ios:d3ca7619e76b319e9f2677',
    messagingSenderId: '167560947670',
    projectId: 'foodpandaclone-f3bdc',
    storageBucket: 'foodpandaclone-f3bdc.appspot.com',
    iosBundleId: 'com.example.sellersApp.RunnerTests',
  );
}
